const itemsFromBackend=[
    {
      componentName:"ec2",
      componentID:"fb88e870-5c89-11ea-bd9c-d56e6ed465b0",
      componentIcon:"ec2-image-link",
      componentDescription:"ec2-desc",
      componentTemplate:{
        $schema:"http://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
        contentVersion:"1.0.0.0",
        parameters:{
          name:{
            type:"string"
          },
          location:{
            type:"string"
          },
          addressPrefix:{
            type:"string"
          },
          enableDdosProtection:{
            type:"bool"
          }
        },
        variables:{
          apiVersion:"2019-09-01"
        },
    }},
    {
      componentName:"ec3",
      componentID:"025ca650-5c8a-11ea-bd9c-d56e6ed465b0",
      componentIcon:"ec2-image-link",
      componentDescription:"ec2-desc",
      componentTemplate:{
        $schema:"http://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
        contentVersion:"1.0.0.0",
        parameters:{
          name:{
            type:"string"
          },
          location:{
            type:"string"
          },
          addressPrefix:{
            type:"string"
          },
          enableDdosProtection:{
            type:"bool"
          }
        },
        variables:{
          apiVersion:"2019-09-01"
        },
    }}
  ]

export default itemsFromBackend; 